cars:
  count: 1000
  arrival_time_min: 1
  arrival_time_max: 2
  main_queue_length_max: 5
stations:
  1:
    count: 4
    serve_time_min: 2
    serve_time_max: 5
    queue_length_max: 3
  2:
    count: 2
    serve_time_min: 3
    serve_time_max: 6
    queue_length_max: 3
  3:
    count: 2
    serve_time_min: 1
    serve_time_max: 4
    queue_length_max: 3
  4:
    count: 2
    serve_time_min: 4
    serve_time_max: 7
    queue_length_max: 3
registers:
  count: 2
  handle_time_min: 1
  handle_time_max: 3
  queue_length_max: 1
